- hosts: web
  become: true
  tasks:
    - name: Install Docker
      amazon.aws.aws_package:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image
      command: docker pull sanikaa5/node-app:latest

    - name: Run Node.js container
      command: docker run -d -p 80:3000 sanikaa5/node-app:latest
